#!/bin/bash

release_file=/etc/os-release
logfiles=/home/gwine0047/projects/bash_scripting/updater.log
errorlog=/home/gwine0047/projects/bash_scripting/updater_errors.log

exit_status() 
{
    if [  $? -ne 0  ]
    then
        echo "An error, please check the $errorlog file."
    fi
}

if grep -q "Arch" $release_file #check or search (-q) don't print anything
then
    echo "This host is based on Arch, and run the pacman update command"
    sudo pacman -Syu >>$logfiles 2>>$errorlog
    exit_status
fi

if grep -q "Ubuntu" $release_file || grep -q "Debian" $release_file
then
    echo "This host is based on Ubuntu or Debian"
    
    sudo apt update >>$logfiles 2>>$errorlog
    exit_status

    sudo apt dist-upgrade >>$logfiles 2>>$errorlog
    exit_status
fi

#you can remove the [ ] for if statement if checking for a terminal command